# ============================================================
# civic.icarm: Example Datasets
# ============================================================

#' Synthetic Civic Voting Dataset
#'
#' @description
#' A synthetic dataset of 1,000 individuals capturing factors associated with
#' voter participation. Constructed to support DataCitizen-Pro teaching goals:
#' demonstrating data literacy, fairness auditing, and democratic judgment
#' in the context of electoral participation modelling.
#'
#' Protected attributes (`gender`, `ethnicity`) are included deliberately for
#' fairness analysis exercises.
#'
#' @format A tibble with 1,000 rows and 10 variables:
#' \describe{
#'   \item{voted}{Factor. Whether the individual voted: `"yes"` or `"no"`.}
#'   \item{age}{Integer. Age in years (18–85).}
#'   \item{education}{Ordered factor. Highest education:
#'     `"primary"`, `"secondary"`, `"vocational"`, `"university"`, `"postgraduate"`.}
#'   \item{income}{Numeric. Monthly net income in EUR (standardised, mean ~0).}
#'   \item{political_interest}{Integer 1–5. Self-reported political interest.}
#'   \item{news_consumption}{Integer. Weekly hours of news consumed (0–20).}
#'   \item{civic_org_member}{Logical. Member of a civic organisation.}
#'   \item{region}{Factor. German federal region (simulated).}
#'   \item{gender}{Factor. Self-reported gender: `"female"`, `"male"`, `"diverse"`.}
#'   \item{migration_background}{Logical. Has a migration background.}
#' }
#'
#' @source Synthetic data generated by the civic.icarm team for teaching purposes.
#'   Distributions are calibrated to approximate German civic participation surveys.
#'
#' @references
#' Awe, O. O. (2025). DataCitizen-Pro DFG Proposal. LUE, Ludwigsburg.
#'
#' @examples
#' data(civic_voting)
#' head(civic_voting)
#' table(civic_voting$voted, civic_voting$gender)
"civic_voting"

#' Synthetic Civic Education Outcomes Dataset
#'
#' @description
#' A synthetic dataset of 800 teacher education students measuring civic
#' knowledge, statistical reasoning, and data literacy competencies. Designed
#' for regression modelling exercises within the DataCitizen-Pro framework.
#'
#' @format A tibble with 800 rows and 9 variables:
#' \describe{
#'   \item{civic_knowledge_score}{Numeric. Score 0–100 on standardised civic
#'     knowledge test.}
#'   \item{data_literacy_score}{Numeric. Score 0–100 on data literacy assessment.}
#'   \item{age}{Integer. Student age (18–45).}
#'   \item{education}{Factor. Prior education level.}
#'   \item{news_consumption}{Integer. Weekly hours of news (0–20).}
#'   \item{stats_course}{Logical. Completed at least one statistics course.}
#'   \item{teaching_subject}{Factor. Primary teaching subject area.}
#'   \item{gender}{Factor. Self-reported gender.}
#'   \item{migration_background}{Logical. Has a migration background.}
#' }
#'
#' @source Synthetic data generated for civic.icarm teaching vignettes.
#'
#' @examples
#' data(civic_education)
#' summary(civic_education$civic_knowledge_score)
"civic_education"

#' German Credit Scoring Dataset (Fairness Benchmark)
#'
#' @description
#' A cleaned version of the classic Statlog (German Credit Data) dataset,
#' used in civic.icarm as a fairness auditing benchmark. This dataset is
#' commonly used to demonstrate discriminatory risk in credit scoring models
#' — a paradigmatic case for democratic judgment discussions.
#'
#' @format A tibble with 1,000 rows and 8 key variables (simplified):
#' \describe{
#'   \item{credit_risk}{Factor. `"good"` or `"bad"` credit risk.}
#'   \item{duration}{Integer. Loan duration in months.}
#'   \item{credit_amount}{Numeric. Loan amount in DM.}
#'   \item{age}{Integer. Applicant age.}
#'   \item{housing}{Factor. Housing status.}
#'   \item{job}{Factor. Job type.}
#'   \item{gender_proxy}{Factor. Synthetic gender proxy (for fairness demos).}
#'   \item{purpose}{Factor. Loan purpose.}
#' }
#'
#' @source
#' Hofmann, H. (1994). Statlog (German Credit Data). UCI Machine Learning Repository.
#' \url{https://archive.ics.uci.edu/ml/datasets/statlog+(german+credit+data)}
#'
#' @examples
#' data(civic_german_credit)
#' table(civic_german_credit$credit_risk, civic_german_credit$gender_proxy)
"civic_german_credit"
